language: python
python:
  - "3.7"

script:
  - coverage run -m unittest -v

after_success:
  - coverage xml
  - bash < (curl -s https://codecov.io/bash)

cache:
  pip: true
  directories:
    - ${HOME}/moose

env:
  global:
    - MOOSE_DIR=${HOME}/moose
    - PYTHONPATH=${MOOSE_DIR}/python:${PYTHONPATH}

install:
  - pip install -r requirements.txt
  # install MOOSE
  - wget https://github.com/idaholab/moose/archive/v1.0.0.tar.gz -O /tmp/moose.tar.gz
  - tar -xvf /tmp/moose.tar.gz -C ${HOME}/moose --strip-components=1
  - cd ${MOOSE_DIR}/framework/contrib/hit
  - make hit
