"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

Notes:
    - if you get an error about missing 'libpython3.5.dylib', make a symlink to 'libpython3.5m.dylib'
"""

from setuptools import setup
import os
from src.consts import *
from glob import glob

pth = os.environ.get("OUTDIR", "/tmp")

APP = ['src/main.py']
APP_NAME = 'Otter'
DATA_FILES = [
    ('icons', glob('src/icons/*.svg')),
    ('plugins', glob('src/plugins/*.py')),
    ('plugins/computed_vs_measured', glob('src/plugins/computed_vs_measured/*.py')),
    ('plugins/csvplotter', glob('src/plugins/csvplotter/*.py')),
    ('plugins/movie', glob('src/plugins/movie/*.py')),
]
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "GUI frontend for chigger",
        'CFBundleIdentifier': "name.andrs.osx.otter",
        'CFBundleVersion': str(VERSION),
        'CFBundleShortVersionString': str(VERSION),
        'NSHumanReadableCopyright': COPYRIGHT
    },
    'bdist_base': pth + '/build',
    'dist_dir': pth + '/dist',
    'packages': [
        'vtk', 'mooseutils', 'chigger'
    ],
    'iconfile': 'icon.icns'
}

setup(
    name = APP_NAME,
    app = APP,
    data_files = DATA_FILES,
    options = {'py2app': OPTIONS},
    setup_requires = ['py2app']
)
