"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

Notes:
    - if you get an error about missing 'libpython3.5.dylib', make a symlink to 'libpython3.5m.dylib'
"""

from setuptools import setup
import otter
from glob import glob

pth = '/Users/andrsd/tmp/otter'

APP = ['main.py']
APP_NAME = 'Otter'
DATA_FILES = [
    ('icons', glob('icons/*.svg'))
]
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "GUI frontend for chigger",
        'CFBundleIdentifier': "name.andrs.osx.otter",
        'CFBundleVersion': str(otter.VERSION),
        'CFBundleShortVersionString': str(otter.VERSION),
        'NSHumanReadableCopyright': otter.COPYRIGHT
    },
    'bdist_base': pth + '/build',
    'dist_dir': pth + '/dist',
    'packages': [
        'vtk'
    ],
    'iconfile': 'icon.icns'
}

setup(
    name = APP_NAME,
    app = APP,
    data_files = DATA_FILES,
    options = {'py2app': OPTIONS},
    setup_requires = ['py2app']
)
