name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      TEST_CI: YES
    runs-on: ubuntu-latest
    name: ubuntu
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup env
        run: |
          echo "PYTHONPATH=${RUNNER_TEMP}/moose-master/python:${PYTHONPATH}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/test.txt
      - name: Install MOOSE
        run: |
          wget https://github.com/idaholab/moose/archive/master.tar.gz -O ${RUNNER_TEMP}/moose.tar.gz -nv
          tar -xf ${RUNNER_TEMP}/moose.tar.gz -C ${RUNNER_TEMP}
          cd ${RUNNER_TEMP}/moose-master/framework/contrib/hit
          make hit
          cd -
      - name: Run tests
        run: |
          coverage run -m unittest -v && coverage xml
      - name: Code coverage
        uses: codecov/codecov-action@v2
