name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    name: ubuntu
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libgl1-mesa-glx libegl1 libglib2.0-0 libxcb-image0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 xserver-xephyr libfontconfig1 libxkbcommon-dev libdbus-1-3 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          sudo apt install xvfb
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements/test.txt
      - name: Run tests
        run: |
          xvfb-run --auto-servernum --server-num=1 --server-args="-screen 1 1920x1200x24 -ac +extension GLX" coverage run --source=otter -m pytest -v -s
          coverage xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-coverage
          path: coverage.xml

  macos:
    env:
      TEST_CI: YES
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    name: macos
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements/test.txt
      - name: Run tests
        run: |
          coverage run --source=otter -m pytest -v -s
          coverage xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-coverage
          path: coverage.xml

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements/test.txt
      - name: Run test
        run: |
          coverage run --source=otter -m pytest -v -s
          coverage xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-coverage
          path: coverage.xml

  upload-to-codecov:
    needs: [linux, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
